name: SonarQube Analysis

on:
  push:
    branches:
      - main  # Set your main branch here
  pull_request:
    branches:
      - main  # Set your main branch here

jobs:
  sonarqube-analysis:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: '11'  # Set your Java version here

    - name: SonarQube Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: "9cf52ab75157509abad1bec9d25a974217e126de"  # Set your SonarQube token as a secret in your repository
