name: SonarQube Analysis

on:
  push:
    branches:
      - main  # Set your main branch here
  pull_request:
    branches:
      - main  # Set your main branch here

jobs:
  sonarqube-analysis:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: '17'  # Set your Java version here

    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
